export const FETCH_MAP = 'FETCH_MAP';
export const FETCH_MAP_SUCCESS = 'FETCH_MAP_SUCCESS';
export const FETCH_MAP_ERROR = 'FETCH_MAP_ERROR';


export const FETCH_MAP_UPDATE = 'FETCH_MAP_UPDATE';
export const FETCH_MAP_CREATE = 'FETCH_MAP_CREATE';


export const FETCH_MAP_CHECKED_ONE = 'FETCH_MAP_CHECKED_ONE';
export const FETCH_MAP_CHECKED_ALL = 'FETCH_MAP_CHECKED_ALL';

export const FETCH_MAP_ACTIVE_ONE = 'FETCH_MAP_ACTIVE_ONE';
export const FETCH_MAP_ACTIVE_ONE_SUCCESS = 'FETCH_MAP_ACTIVE_ONE_SUCCESS';

export const FETCH_MAP_ACTIVE_ALL = 'FETCH_MAP_ACTIVE_ALL';
export const FETCH_MAP_ACTIVE_ALL_SUCCESS = 'FETCH_MAP_ACTIVE_ALL_SUCCESS';

export const FETCH_MAP_DELETE_ALL = 'FETCH_MAP_DELETE_ALL';