export const FETCH_SUPPORT = 'FETCH_SUPPORT';
export const FETCH_SUPPORT_SUCCESS = 'FETCH_SUPPORT_SUCCESS';
export const FETCH_SUPPORT_ERROR = 'FETCH_SUPPORT_ERROR';


export const FETCH_SUPPORT_UPDATE = 'FETCH_SUPPORT_UPDATE';
export const FETCH_SUPPORT_CREATE = 'FETCH_SUPPORT_CREATE';


export const FETCH_SUPPORT_CHECKED_ONE = 'FETCH_SUPPORT_CHECKED_ONE';
export const FETCH_SUPPORT_CHECKED_ALL = 'FETCH_SUPPORT_CHECKED_ALL';

export const FETCH_SUPPORT_ACTIVE_ONE = 'FETCH_SUPPORT_ACTIVE_ONE';
export const FETCH_SUPPORT_ACTIVE_ONE_SUCCESS = 'FETCH_SUPPORT_ACTIVE_ONE_SUCCESS';

export const FETCH_SUPPORT_ACTIVE_ALL = 'FETCH_SUPPORT_ACTIVE_ALL';
export const FETCH_SUPPORT_ACTIVE_ALL_SUCCESS = 'FETCH_SUPPORT_ACTIVE_ALL_SUCCESS';

export const FETCH_SUPPORT_DELETE_ALL = 'FETCH_SUPPORT_DELETE_ALL';

export const CHECK_PROCESS_SUPPORT_ONE = 'CHECK_PROCESS_SUPPORT_ONE';
export const CHECK_PROCESS_SUPPORT_ALL = 'CHECK_PROCESS_SUPPORT_ALL';
export const SHOW_DETAIL_SUPPORT = 'SHOW_DETAIL_SUPPORT';
export const SHOW_DETAIL_SUPPORT_SUCCESS = 'SHOW_DETAIL_SUPPORT_SUCCESS';