export const FETCH_DASHBOARD = 'FETCH_DASHBOARD';
export const FETCH_DASHBOARD_SUCCESS = 'FETCH_DASHBOARD_SUCCESS';
export const CHANGE_PASSWORD_HOME = 'CHANGE_PASSWORD_HOME';
export const FETCH_LOGOUT = 'FETCH_LOGOUT';