export const REQUEST_LOGIN = 'REQUEST_LOGIN';
export const REQUEST_LOGIN_FAILED = 'REQUEST_LOGIN_FAILED';
export const REQUEST_LOGIN_SUCCESS = 'REQUEST_LOGIN_SUCCESS';

export const REQUEST_RESETPASS = 'REQUEST_RESETPASS';
export const REQUEST_RESETPASS_FAILED = 'REQUEST_RESETPASS_FAILED';
export const REQUEST_RESETPASS_SUCCESS = 'REQUEST_RESETPASS_CUCCESS';

export const REQUEST_CHANGEPASS = 'REQUEST_CHANGEPASS';
export const REQUEST_CHANGEPASS_FAILED = 'REQUEST_CHANGEPASS_FAILED';
export const REQUEST_CHANGEPASS_SUCCESS = 'REQUEST_CHANGEPASS_SUCCESS';
export const REQUEST_CHECKTOKEN = 'REQUEST_CHECKTOKEN';


export const SHOW_LOADING = 'SHOW_LOADING';
export const SHOW_SUBMIT = 'SHOW_SUBMIT';

export const SHOW_SUBMITFORM = 'SHOW_SUBMITFORM';

export const SHOW_SEARCH = 'SHOW_SEARCH';

