export const FETCH_GROUP_TITLE = 'FETCH_GROUP_TITLE';
export const FETCH_GROUP_TITLE_SUCCESS = 'FETCH_GROUP_TITLE_SUCCESS';
export const FETCH_GROUP_TITLE_ERROR = 'FETCH_GROUP_TITLE_ERROR';


export const FETCH_GROUP_TITLE_UPDATE = 'FETCH_GROUP_TITLE_UPDATE';
export const FETCH_GROUP_TITLE_CREATE = 'FETCH_GROUP_TITLE_CREATE';


export const FETCH_GROUP_TITLE_CHECKED_ONE = 'FETCH_GROUP_TITLE_CHECKED_ONE';
export const FETCH_GROUP_TITLE_CHECKED_ALL = 'FETCH_GROUP_TITLE_CHECKED_ALL';

export const FETCH_GROUP_TITLE_ACTIVE_ONE = 'FETCH_GROUP_TITLE_ACTIVE_ONE';
export const FETCH_GROUP_TITLE_ACTIVE_ONE_SUCCESS = 'FETCH_GROUP_TITLE_ACTIVE_ONE_SUCCESS';

export const FETCH_GROUP_TITLE_ACTIVE_ALL = 'FETCH_GROUP_TITLE_ACTIVE_ALL';
export const FETCH_GROUP_TITLE_ACTIVE_ALL_SUCCESS = 'FETCH_GROUP_TITLE_ACTIVE_ALL_SUCCESS';

export const FETCH_GROUP_TITLE_DELETE_ALL = 'FETCH_GROUP_TITLE_DELETE_ALL';