export const FETCH_POSTS = 'FETCH_POSTS';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_ERROR = 'FETCH_POSTS_ERROR';


export const FETCH_POSTS_UPDATE = 'FETCH_POSTS_UPDATE';
export const FETCH_POSTS_CREATE = 'FETCH_POSTS_CREATE';


export const FETCH_POSTS_CHECKED_ONE = 'FETCH_POSTS_CHECKED_ONE';
export const FETCH_POSTS_CHECKED_ALL = 'FETCH_POSTS_CHECKED_ALL';

export const FETCH_POSTS_ACTIVE_ONE = 'FETCH_POSTS_ACTIVE_ONE';
export const FETCH_POSTS_ACTIVE_ONE_SUCCESS = 'FETCH_POSTS_ACTIVE_ONE_SUCCESS';

export const FETCH_POSTS_ACTIVE_ALL = 'FETCH_POSTS_ACTIVE_ALL';
export const FETCH_POSTS_ACTIVE_ALL_SUCCESS = 'FETCH_POSTS_ACTIVE_ALL_SUCCESS';

export const FETCH_POSTS_DELETE_ALL = 'FETCH_POSTS_DELETE_ALL';
export const FETCH_GET_POSTS_UPDATE = 'FETCH_GET_POSTS_UPDATE';
export const FETCH_GET_POSTS_UPDATE_SUCCESS = 'FETCH_GET_POSTS_UPDATE_SUCCESS';

export const GET_LIST_TITLE_GROUP = 'GET_LIST_TITLE_GROUP';
export const GET_LIST_TITLE_GROUP_SUCCESS = 'GET_LIST_TITLE_GROUP_SUCCESS';

export const DELETE_IMAGE_SLIDE = 'DELETE_IMAGE_SLIDE';
export const DELETE_IMAGE_SLIDE_SUCCESS = 'DELETE_IMAGE_SLIDE_SUCCESS';