export const FETCH_MENUTYPE = 'FETCH_MENUTYPE';
export const FETCH_MENUTYPE_SUCCESS = 'FETCH_MENUTYPE_SUCCESS';
export const FETCH_MENUTYPE_ERROR = 'FETCH_MENUTYPE_ERROR';


export const FETCH_MENUTYPE_UPDATE = 'FETCH_MENUTYPE_UPDATE';
export const FETCH_MENUTYPE_CREATE = 'FETCH_MENUTYPE_CREATE';


export const FETCH_MENUTYPE_CHECKED_ONE = 'FETCH_MENUTYPE_CHECKED_ONE';
export const FETCH_MENUTYPE_CHECKED_ALL = 'FETCH_MENUTYPE_CHECKED_ALL';

export const FETCH_MENUTYPE_ACTIVE_ONE = 'FETCH_MENUTYPE_ACTIVE_ONE';
export const FETCH_MENUTYPE_ACTIVE_ONE_SUCCESS = 'FETCH_MENUTYPE_ACTIVE_ONE_SUCCESS';

export const FETCH_MENUTYPE_ACTIVE_ALL = 'FETCH_MENUTYPE_ACTIVE_ALL';
export const FETCH_MENUTYPE_ACTIVE_ALL_SUCCESS = 'FETCH_MENUTYPE_ACTIVE_ALL_SUCCESS';

export const FETCH_MENUTYPE_DELETE_ALL = 'FETCH_MENUTYPE_DELETE_ALL';

// list menu

export const GET_MENU = 'GET_MENU';
export const GET_MENU_SUCCESS = 'GET_MENU_SUCCESS';
export const CHECK_SLUG = 'CHECK_SLUG';
export const CHECK_SLUG_SUCCESS = 'CHECK_SLUG_SUCCESS';
export const GET_LIST_CATEGORY = 'GET_LIST_CATEGORY';
export const GET_LIST_CATEGORY_SUCCESS = 'GET_LIST_CATEGORY_SUCCESS';

export const ADD_MENU ='ADD_MENU';
export const EDIT_MENU ='EDIT_MENU';
export const ACTIVE_MENU = 'ACTIVE_MENU';
export const ACTIVE_MENU_SUCCESS = 'ACTIVE_MENU_SUCCESS';
export const DELETE_MENU = 'DELETE_MENU';
export const CHANGE_MENU = 'CHANGE_MENU';

export const LOAD_PERMISION = 'LOAD_PERMISION';
export const LOAD_PERMISION_SUCCESS = 'LOAD_PERMISION_SUCCESS';
export const CHECK_ONE_PERMISSION = 'CHECK_ONE_PERMISSION';
export const CHECK_ALL_PERMISSION = 'CHECK_ALL_PERMISSION';
export const SAVE_PERMISSION = 'SAVE_PERMISSION';