export const FETCH_SLIDER = 'FETCH_SLIDER';
export const FETCH_SLIDER_SUCCESS = 'FETCH_SLIDER_SUCCESS';
export const FETCH_SLIDER_ERROR = 'FETCH_SLIDER_ERROR';

export const FETCH_GET_SLIDER_UPDATE = 'FETCH_GET_SLIDER_UPDATE';
export const FETCH_SLIDER_UPDATE = 'FETCH_SLIDER_UPDATE';
export const FETCH_GET_SLIDER_UPDATE_SUCCESS = 'FETCH_GET_SLIDER_UPDATE_SUCCESS';
export const FETCH_SLIDER_CREATE = 'FETCH_SLIDER_CREATE';


export const FETCH_SLIDER_CHECKED_ONE = 'FETCH_SLIDER_CHECKED_ONE';
export const FETCH_SLIDER_CHECKED_ALL = 'FETCH_SLIDER_CHECKED_ALL';

export const FETCH_SLIDER_ACTIVE_ONE = 'FETCH_SLIDER_ACTIVE_ONE';
export const FETCH_SLIDER_ACTIVE_ONE_SUCCESS = 'FETCH_SLIDER_ACTIVE_ONE_SUCCESS';

export const FETCH_SLIDER_ACTIVE_ALL = 'FETCH_SLIDER_ACTIVE_ALL';
export const FETCH_SLIDER_ACTIVE_ALL_SUCCESS = 'FETCH_SLIDER_ACTIVE_ALL_SUCCESS';

export const FETCH_SLIDER_DELETE_ALL = 'FETCH_SLIDER_DELETE_ALL';