export const FETCH_STEPS = 'FETCH_STEPS';
export const FETCH_STEPS_SUCCESS = 'FETCH_STEPS_SUCCESS';
export const FETCH_STEPS_ERROR = 'FETCH_STEPS_ERROR';

export const FETCH_GET_STEPS_UPDATE = 'FETCH_GET_STEPS_UPDATE';
export const FETCH_STEPS_UPDATE = 'FETCH_STEPS_UPDATE';
export const FETCH_GET_STEPS_UPDATE_SUCCESS = 'FETCH_GET_STEPS_UPDATE_SUCCESS';
export const FETCH_STEPS_CREATE = 'FETCH_STEPS_CREATE';


export const FETCH_STEPS_CHECKED_ONE = 'FETCH_STEPS_CHECKED_ONE';
export const FETCH_STEPS_CHECKED_ALL = 'FETCH_STEPS_CHECKED_ALL';

export const FETCH_STEPS_ACTIVE_ONE = 'FETCH_STEPS_ACTIVE_ONE';
export const FETCH_STEPS_ACTIVE_ONE_SUCCESS = 'FETCH_STEPS_ACTIVE_ONE_SUCCESS';

export const FETCH_STEPS_ACTIVE_ALL = 'FETCH_STEPS_ACTIVE_ALL';
export const FETCH_STEPS_ACTIVE_ALL_SUCCESS = 'FETCH_STEPS_ACTIVE_ALL_SUCCESS';

export const FETCH_STEPS_DELETE_ALL = 'FETCH_STEPS_DELETE_ALL';