export const FETCH_GROUPS = 'FETCH_GROUPS';
export const FETCH_GROUPS_SUCCESS = 'FETCH_GROUPS_SUCCESS';
export const FETCH_GROUPS_ERROR = 'FETCH_GROUPS_ERROR';


export const FETCH_GROUPS_UPDATE = 'FETCH_GROUPS_UPDATE';
export const FETCH_GROUPS_CREATE = 'FETCH_GROUPS_CREATE';


export const FETCH_GROUPS_CHECKED_ONE = 'FETCH_GROUPS_CHECKED_ONE';
export const FETCH_GROUPS_CHECKED_ALL = 'FETCH_GROUPS_CHECKED_ALL';

export const FETCH_GROUPS_ACTIVE_ONE = 'FETCH_GROUPS_ACTIVE_ONE';
export const FETCH_GROUPS_ACTIVE_ONE_SUCCESS = 'FETCH_GROUPS_ACTIVE_ONE_SUCCESS';

export const FETCH_GROUPS_ACTIVE_ALL = 'FETCH_GROUPS_ACTIVE_ALL';
export const FETCH_GROUPS_ACTIVE_ALL_SUCCESS = 'FETCH_GROUPS_ACTIVE_ALL_SUCCESS';

export const FETCH_GROUPS_DELETE_ALL = 'FETCH_GROUPS_DELETE_ALL';


export const GROUP_ACTIVE_MENU = 'GROUP_ACTIVE_MENU';
export const GROUP_GET_MENU = 'GROUP_GET_MENU';
export const GROUP_GET_MENU_SUCCESS = 'GROUP_GET_MENU_SUCCESS';
export const GROUP_LOAD_PERMISION = 'GROUP_LOAD_PERMISION';
export const GROUP_LOAD_PERMISION_SUCCESS = 'GROUP_LOAD_PERMISION_SUCCESS';
export const GROUP_CHECK_ALL_PERMISSION = 'GROUP_CHECK_ALL_PERMISSION';
export const GROUP_CHECK_ONE_PERMISSION = 'GROUP_CHECK_ONE_PERMISSION';
export const GROUP_SAVE_PERMISSION = 'GROUP_SAVE_PERMISSION';