export const FETCH_LISTPERMISSION = 'FETCH_LISTPERMISSION';
export const FETCH_LISTPERMISSION_SUCCESS = 'FETCH_LISTPERMISSION_SUCCESS';
export const FETCH_LISTPERMISSION_ERROR = 'FETCH_LISTPERMISSION_ERROR';


export const FETCH_LISTPERMISSION_UPDATE = 'FETCH_LISTPERMISSION_UPDATE';
export const FETCH_LISTPERMISSION_CREATE = 'FETCH_LISTPERMISSION_CREATE';


export const FETCH_LISTPERMISSION_CHECKED_ONE = 'FETCH_LISTPERMISSION_CHECKED_ONE';
export const FETCH_LISTPERMISSION_CHECKED_ALL = 'FETCH_LISTPERMISSION_CHECKED_ALL';

export const FETCH_LISTPERMISSION_ACTIVE_ONE = 'FETCH_LISTPERMISSION_ACTIVE_ONE';
export const FETCH_LISTPERMISSION_ACTIVE_ONE_SUCCESS = 'FETCH_LISTPERMISSION_ACTIVE_ONE_SUCCESS';

export const FETCH_LISTPERMISSION_ACTIVE_ALL = 'FETCH_LISTPERMISSION_ACTIVE_ALL';
export const FETCH_LISTPERMISSION_ACTIVE_ALL_SUCCESS = 'FETCH_LISTPERMISSION_ACTIVE_ALL_SUCCESS';

export const FETCH_LISTPERMISSION_DELETE_ALL = 'FETCH_LISTPERMISSION_DELETE_ALL';