export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_ERROR = 'FETCH_USERS_ERROR';


export const FETCH_USERS_UPDATE = 'FETCH_USERS_UPDATE';
export const FETCH_USERS_CREATE = 'FETCH_USERS_CREATE';


export const FETCH_USERS_CHECKED_ONE = 'FETCH_USERS_CHECKED_ONE';
export const FETCH_USERS_CHECKED_ALL = 'FETCH_USERS_CHECKED_ALL';

export const FETCH_USERS_ACTIVE_ONE = 'FETCH_USERS_ACTIVE_ONE';
export const FETCH_USERS_ACTIVE_ONE_SUCCESS = 'FETCH_USERS_ACTIVE_ONE_SUCCESS';

export const FETCH_USERS_ACTIVE_ALL = 'FETCH_USERS_ACTIVE_ALL';
export const FETCH_USERS_ACTIVE_ALL_SUCCESS = 'FETCH_USERS_ACTIVE_ALL_SUCCESS';

export const FETCH_USERS_DELETE_ALL = 'FETCH_USERS_DELETE_ALL';

export  const FETCH_USERNAME_CHECK_UNIQUE = 'FETCH_USERNAME_CHECK_UNIQUE';

export  const FETCH_EMAIL_CHECK_UNIQUE = 'FETCH_EMAIL_CHECK_UNIQUE';
export  const FETCH_EMAIL_CHECK_UNIQUE_SUCCESS = 'FETCH_EMAIL_CHECK_UNIQUE_SUCCESS';
export const FETCH_USERNAME_CHECK_UNIQUE_SUCCESS = 'FETCH_USERNAME_CHECK_UNIQUE_SUCCESS';
export const FETCH_LIST_GROUP = 'FETCH_LIST_GROUP';
export const FETCH_LIST_GROUP_SUCCESS = 'FETCH_LIST_GROUP_SUCCESS';