export const FETCH_AREA = 'FETCH_AREA';
export const FETCH_AREA_SUCCESS = 'FETCH_AREA_SUCCESS';
export const FETCH_AREA_ERROR = 'FETCH_AREA_ERROR';


export const FETCH_AREA_UPDATE = 'FETCH_AREA_UPDATE';
export const FETCH_AREA_CREATE = 'FETCH_AREA_CREATE';


export const FETCH_AREA_CHECKED_ONE = 'FETCH_AREA_CHECKED_ONE';
export const FETCH_AREA_CHECKED_ALL = 'FETCH_AREA_CHECKED_ALL';

export const FETCH_AREA_ACTIVE_ONE = 'FETCH_AREA_ACTIVE_ONE';
export const FETCH_AREA_ACTIVE_ONE_SUCCESS = 'FETCH_AREA_ACTIVE_ONE_SUCCESS';

export const FETCH_AREA_ACTIVE_ALL = 'FETCH_AREA_ACTIVE_ALL';
export const FETCH_AREA_ACTIVE_ALL_SUCCESS = 'FETCH_AREA_ACTIVE_ALL_SUCCESS';

export const FETCH_AREA_DELETE_ALL = 'FETCH_AREA_DELETE_ALL';