export const FETCH_PROFILE = 'FETCH_PROFILE';
export const FETCH_PROFILE_SUCCESS = 'FETCH_PROFILE_SUCCESS';
export const FETCH_PROFILE_ERROR = 'FETCH_PROFILE_ERROR';


export const FETCH_PROFILE_CHECKED_ONE = 'FETCH_PROFILE_CHECKED_ONE';
export const FETCH_PROFILE_CHECKED_ALL = 'FETCH_PROFILE_CHECKED_ALL';



export const FETCH_PROFILE_DELETE_ALL = 'FETCH_PROFILE_DELETE_ALL';

export const CHECK_PROCESS_ONE = 'CHECK_PROCESS_ONE';
export const CHECK_PROCESS_ALL = 'CHECK_PROCESS_ALL';

export const SHOW_DETAIL_PROFILE = 'SHOW_DETAIL_PROFILE';
export const SHOW_DETAIL_PROFILE_SUCCESS = 'SHOW_DETAIL_PROFILE_SUCCESS';
export const EXPORT_EXCEL_PROFILE = 'EXPORT_EXCEL_PROFILE';
