export const FETCH_RECRUIT = 'FETCH_RECRUIT';
export const FETCH_RECRUIT_SUCCESS = 'FETCH_RECRUIT_SUCCESS';
export const FETCH_RECRUIT_ERROR = 'FETCH_RECRUIT_ERROR';


export const FETCH_RECRUIT_UPDATE = 'FETCH_RECRUIT_UPDATE';
export const FETCH_RECRUIT_CREATE = 'FETCH_RECRUIT_CREATE';


export const FETCH_RECRUIT_CHECKED_ONE = 'FETCH_RECRUIT_CHECKED_ONE';
export const FETCH_RECRUIT_CHECKED_ALL = 'FETCH_RECRUIT_CHECKED_ALL';

export const FETCH_RECRUIT_ACTIVE_ONE = 'FETCH_RECRUIT_ACTIVE_ONE';
export const FETCH_RECRUIT_ACTIVE_ONE_SUCCESS = 'FETCH_RECRUIT_ACTIVE_ONE_SUCCESS';

export const FETCH_RECRUIT_ACTIVE_ALL = 'FETCH_RECRUIT_ACTIVE_ALL';
export const FETCH_RECRUIT_ACTIVE_ALL_SUCCESS = 'FETCH_RECRUIT_ACTIVE_ALL_SUCCESS';

export const FETCH_RECRUIT_DELETE_ALL = 'FETCH_RECRUIT_DELETE_ALL';

export const GET_ADD_RECRUIT = 'GET_ADD_RECRUIT';
export const GET_ADD_RECRUIT_SUCCESS = 'GET_ADD_RECRUIT_SUCCESS';

export const GET_EDIT_RECRUIT = 'GET_EDIT_RECRUIT';
export const GET_EDIT_RECRUIT_SUCCESS = 'GET_EDIT_RECRUIT_SUCCESS';

export const SHOW_DETAIL_RECRUIT = 'SHOW_DETAIL_RECRUIT';
export const SHOW_DETAIL_RECRUIT_SUCCESS = 'SHOW_DETAIL_RECRUIT_SUCCESS';

export const EXPORT_EXCEL_RECRUIT = 'EXPORT_EXCEL_RECRUIT';