export const FETCH_VACANCIES = 'FETCH_VACANCIES';
export const FETCH_VACANCIES_SUCCESS = 'FETCH_VACANCIES_SUCCESS';
export const FETCH_VACANCIES_ERROR = 'FETCH_VACANCIES_ERROR';


export const FETCH_VACANCIES_UPDATE = 'FETCH_VACANCIES_UPDATE';
export const FETCH_VACANCIES_CREATE = 'FETCH_VACANCIES_CREATE';


export const FETCH_VACANCIES_CHECKED_ONE = 'FETCH_VACANCIES_CHECKED_ONE';
export const FETCH_VACANCIES_CHECKED_ALL = 'FETCH_VACANCIES_CHECKED_ALL';

export const FETCH_VACANCIES_ACTIVE_ONE = 'FETCH_VACANCIES_ACTIVE_ONE';
export const FETCH_VACANCIES_ACTIVE_ONE_SUCCESS = 'FETCH_VACANCIES_ACTIVE_ONE_SUCCESS';

export const FETCH_VACANCIES_ACTIVE_ALL = 'FETCH_VACANCIES_ACTIVE_ALL';
export const FETCH_VACANCIES_ACTIVE_ALL_SUCCESS = 'FETCH_VACANCIES_ACTIVE_ALL_SUCCESS';

export const FETCH_VACANCIES_DELETE_ALL = 'FETCH_VACANCIES_DELETE_ALL';